### ISSUE TITLE
Version 3.0 of this Bundle

### ISSUE THREAD

**Issue by florianv** [florianv/symfony-swap#12]
We need to support Swap 3 and Symfony 3

**Comment by ruudk** [comment]
Any news on this 🙏 ?

**Comment by florianv** [comment]
Not yet, it seems I won't have time to implement it in the following weeks..
It should be quite similar to the current implementation, with some services and class names changes

**Comment by ruudk** [comment]
Just started a new project and was looking to see if I could use this bundle, but nope :( Hope you find time one day :v:

**Comment by florianv** [comment]
@ruudk Thanks to @ekyna, Swap 3 is now supported 🎉

**Comment by ruudk** [comment]
Great! Thanks
