### ISSUE TITLE
Install documentation needs update?

### ISSUE THREAD

**Issue by Pharkie** [florianv/symfony-swap#15]
The command listed for install says:
`composer require florianv/symfony-swap php-http/message php-http/guzzle6-adapter`
This gives 
```
[InvalidArgumentException]
  Could not find a matching version of package florianv/symfony-swap. Check the package spelling, your version constr
  aint and that the package is available in a stability which matches your minimum-stability (stable).
```
I tried
`composer require florianv/swap-bundle php-http/message php-http/guzzle6-adapter`
and that seemed to work better?

**Comment by florianv** [comment]
Yes that's right @Pharkie, the documentation is wrong!

**Comment by florianv** [comment]
Fixed! Thanks ;)
