### ISSUE TITLE
Add new tag for Symfony4 support

### ISSUE THREAD

**Issue by edamov** [florianv/symfony-swap#18]
Hello!

As I can see this bundle already has support Symfony 4 in master branch.
But I can't install this bundle in Symfony 4 application because master is unstable and composer try to find only stable tags when I run `composer require florianv/swap-bundle`
Can you please add new tag for changes which add support Symfony 4?

**Comment by florianv** [comment]
Hey @edamov,

Indeed there was no release after the Symfony 4 support. Should be fixed now by `3.2.0` :)
