### ISSUE TITLE
exchange_rates_api in bundle configuration

### ISSUE THREAD

**Issue by mheki** [florianv/symfony-swap#33]
Hello,
is there any reason `exchange_rates_api` provider is not added to https://github.com/florianv/symfony-swap/blob/master/DependencyInjection/Configuration.php#L74-L80 ?

Thanks

**Comment by jaikdean** [comment]
I think it's because that API was only added to `florianv/exchanger` in 2.2.0, but the dependency chain of this package only depends on `florianv/exchanger:^2.0`. I'd really like to use this API in a Symfony project. Could it be added here regardless of the version issue?

**Comment by jaikdean** [comment]
This is now available.
