### ISSUE TITLE
xChangeApi.com support not allowed in Symfony configuration

### ISSUE THREAD

**Issue by jaikdean** [florianv/symfony-swap#40]
#39 added support for xChangeApi.com, but appears to have missed the required change in `Florianv\SwapBundle\DependencyInjection\Configuration`, despite there being a test added for it.

**Comment by reanim8ed** [comment]
The bug appears because florianv_swap configuration for xchangeapi specifies option as `api-key`, `Service\XchangeApi.php` also does so. But `DependencyInjection\Configuration` expects configuration to have `api_key`value. Mismatch of option values happens.

**Comment by florianv** [comment]
Can you please send a PR to fix it? If it doesn't work as-is...
