### ISSUE TITLE
Unknown named parameter $rates

### ISSUE THREAD

**Issue by potibm** [florianv/symfony-swap#48]
Using the current versions under PHP 8

```
florianv/exchanger                    2.7.2     Currency exchange rates framework for PHP
florianv/swap                         4.3.0     Exchange rates library for PHP
florianv/swap-bundle                  5.3.1     Integrates the Swap library with Symfony
```

with the default config the error above appears.

To me the the (required) PhpArray key should not be `rates` but `latestRates` in the config.

Anything I am missing here?

**Comment by luscinium** [comment]
See https://github.com/florianv/symfony-swap/pull/49
